### ISSUE TITLE
quickrand:seed/0 fails on <R20

### ISSUE THREAD

**Issue by hlieberman** [okeuday/quickrand#5]
Hello!

It looks like quickrand:seed/0 doesn't work on OTP versions less than 20.

This is because quickrand:seed_rand/3 attempts to call rand:seed/2 using the `exsp` parameter that is not defined in OTP < 20.  (This is src/quickrand.erl:373)

There is an ifdef in place to try and catch this situation, but it's currently short-circuited to true.  Perhaps a commit got lost somewhere along the way?

**Comment by okeuday** [comment]
@hlieberman The builds show otherwise https://travis-ci.org/okeuday/quickrand

You can see the version macros here https://github.com/okeuday/quickrand/blob/1c60daa4b0edcec0a6b8310443574baac962ea88/rebar.config#L6-L10

Those macros go into an ifdef/else check here https://github.com/okeuday/quickrand/blob/1c60daa4b0edcec0a6b8310443574baac962ea88/src/quickrand.erl#L51-L64 to determine what version features are available

Which are used at https://github.com/okeuday/quickrand/blob/1c60daa4b0edcec0a6b8310443574baac962ea88/src/quickrand.erl#L371-L384 which specifically checks that there are Erlang/OTP 20 features before using the `exsp` parameter.

If rebar is broken, that may not work.
