### ISSUE TITLE
Global state instead of per process state [ENHANCEMENT]

### ISSUE THREAD

**Issue by yhafri** [okeuday/quickrand#6]
Hi Michael

Is there any downside to cache the state within [quickrand_cache:init/1](https://github.com/okeuday/quickrand/blob/master/src/quickrand_cache.erl#L220-L222) in a global cache?

```erlang
_ = erlang:put(?TUPLE_PDICT_KEY, state_to_tuple(new(Options))),
```

Something along these lines `quickrand_cache:init_/1`:
```erlang
-spec init_(Options :: options()) ->
    ok.
init_(Options) ->
    persistent_term:put(?TUPLE_PDICT_KEY, state_to_tuple(new(Options))).
```

Then, add this new [quickrand_cache:rand_bytes_/1](https://github.com/okeuday/quickrand/blob/master/src/quickrand_cache.erl#L258-L266):

```erlang
-spec rand_bytes_(N :: pos_integer()) ->
    binary().

rand_bytes_(N)
    when is_integer(N), N > 0 ->
    {I, CacheSize, Cache} = persistent_term:get(?TUPLE_PDICT_KEY),
    {Bytes, NewI, NewCache} = bytes_get(N, I, CacheSize, Cache),
    %% !!! don't know what can be done here as persistent_term:put/2 is really slow (triggers GC) !!!
    ok = persistent_term:put(?TUPLE_PDICT_KEY, {NewI, CacheSize, NewCache}),
    Bytes.
```
My application is heavily using your `uuid` module to generate `v4` UUIDs.
While checking your code today i realized that you've added a nice [caching layer](https://github.com/okeuday/uuid/blob/master/src/uuid.erl#L560-L567
) to it.

I'm generating about _10 million_ v4 UUIDs per day and would like to switch to `uuid:get_v4(cached_)`:

```erlang
get_v4(cached) ->
    <<Rand1:48, _:4, Rand2:12, _:2, Rand3:62>> =
        quickrand_cache:rand_bytes_(16),
    <<Rand1:48,
      0:1, 1:1, 0:1, 0:1,  % version 4 bits
      Rand2:12,
      1:1, 0:1,            % RFC 4122 variant bits
      Rand3:62>>;
```

With this in place, all my processes will use the same cached state and will avoid to store extra data in their process dictionnary:

```erlang
ok = quickrand_cache:init_([{cache_size, 16}]),
[...]
V4 = uuid:get_v4(cached),
```
Any issue with this?

Thanks.

**Comment by okeuday** [comment]
Hi Younès,

The problem with global state is that it always limits scalability, even despite the best efforts of the Erlang/OTP team (and external researchers) to make `ets` and `persistent_term` efficient.  That problem isn't something that is really solvable, except by relying on low-level atomic operations (and using Erlang keeps you from that lower-level development unless NIFs and/or port drivers are used which sabotage the fault-tolerance Erlang is meant to provide, unless the NIFs/port-drivers are dead code).

The `persistent_term` module is meant for read-only global data, so it would cause performance problems if it was used for `quickrand_cache` data (due to the need to update the cached random data).  `ets` could be used, but it is more efficient to utilize the Erlang process heap data.  The `quickrand_cache` data consumes more memory, but normally that is not a problem.  For there to be a benefit (to using the `quickrand_cache` data), the Erlang processes would need to generate more than 1 v4 UUID during their lifetime (testing is required to understand the benefit and it is possible to tune the size of the cache, with the `quickrand_cache:new/1` option or the application env `cache_size` value).

There are two ways of using `quickrand_cache`, either with the process dictionary usage, or without by providing the `quickrand_cache` state variable.  If you wanted to use `uuid:get_v4/1` with the `quickrand_cache` state variable, you would need to create it with `quickrand_cache:new/0` or `quickrand_cache:new/1`.  I haven't seen a large performance difference between the two ways of using the `quickrand_cache` but using the state variable (not using the process dictionary) should be more efficient and it is better to avoid using the process dictionary when you are able to do so.

**Comment by yhafri** [comment]
> [...]
> There are two ways of using `quickrand_cache`, either with the process dictionary usage, or without by providing the `quickrand_cache` state variable. If you wanted to use `uuid:get_v4/1` with the `quickrand_cache` state variable, you would need to create it with `quickrand_cache:new/0` or `quickrand_cache:new/1`. I haven't seen a large performance difference between the two ways of using the `quickrand_cache` but using the state variable (not using the process dictionary) should be more efficient and it is better to avoid using the process dictionary when you are able to do so.

Great feedback Michael. I will `quickrand_cache state variable`  a got and let you know.
